### ISSUE TITLE
deploy get_ip gets the wrong ip address

### ISSUE THREAD

**Issue by brunogoossens** [shipyard/shipyard-project.com#24]
The deploy script fails because the get_ip function gets the wrong ip address.

if I do
```
$ docker run --rm --net=host alpine ip route
```
This is the output:
```
159.253.5.0/24 dev eth0  src 159.253.5.117
172.17.0.0/16 dev docker0  src 172.17.42.1
```
If I do the command in the script
```
$ docker run --rm --net=host alpine ip route get 8.8.8.8 | awk '{ print $7;  }'
```
This is the output:
```
159.253.5.117
```
The script stays in the waiting loop.

If I hardcode the correct ip 172.17.42.1 then the installation succeeds.
```
$ lsb_release
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```

I dont use docker swarm. Just a simple docker install on my VPS

**Comment by brunogoossens** [comment]
maybe something like this may do the trick:

```
docker run --rm --net=host alpine ifconfig docker0 | grep 'inet addr:' | cut -d: -f2  | awk '{ print $1}'
```

**Comment by ehazlett** [comment]
Yes unfortunately detecting the proper IP will never be exact as there is
no way to detect exactly what IP is expected (internal, public, which nic,
etc).  You can use the "IP" env var when deploying to set.  For example:

curl shipyard-project.com | IP=1.2.3.4 bash -s
